name: chatclient
description: A new Flutter project.

version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  signalr_netcore:
    path: ../

  logging: ^1.2.0
  rxdart: ^0.27.7
  quiver: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
